### ISSUE TITLE
Resizable previews crashes application

### ISSUE THREAD

**Issue by Eilhart** [AliceCA/Overchan-Android#7]
Downloading preview image from OP of this thread https://2ch.hk/mobi/res/1002399.html causes Runtime Exception.

**Comment by Eilhart** [comment]
Here's logcat output:
```
12-31 16:42:12.635 27857 27857 W Bitmap  : Called getWidth() on a recycle()'d bitmap! This is undefined behavior!
12-31 16:42:12.635 27857 27857 W Bitmap  : Called getHeight() on a recycle()'d bitmap! This is undefined behavior!
12-31 16:42:12.635 27857 27857 W Bitmap  : Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
12-31 16:42:12.635 27857 27857 W Bitmap  : Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
12-31 16:42:12.678 27857 27857 D AndroidRuntime: Shutting down VM
12-31 16:42:12.693 27857 27857 E AndroidRuntime: FATAL EXCEPTION: main
12-31 16:42:12.693 27857 27857 E AndroidRuntime: Process: unofficial.nya.miku.wishmaster, PID: 27857
12-31 16:42:12.693 27857 27857 E AndroidRuntime: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@13aa7fd
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.graphics.Canvas.drawBitmap(Canvas.java:1404)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:544)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.widget.ImageView.onDraw(ImageView.java:1228)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.draw(View.java:16184)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15180)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15175)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15175)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15175)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15175)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.widget.ListView.drawChild(ListView.java:3418)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.widget.AbsListView.dispatchDraw(AbsListView.java:2615)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.widget.ListView.dispatchDraw(ListView.java:3413)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.draw(View.java:16187)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.widget.AbsListView.draw(AbsListView.java:4166)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15180)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.draw(View.java:16187)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15180)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15175)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.draw(View.java:16187)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15180)
12-31 16:42:12.693 27857 27857 E AndroidRuntime: 	at android.view.View.draw(View.java:15954)

```
